services:
    backend:
        build: ../backend
        ports:
            - "3001:3001"

    frontend:
        build: .
        ports:
            - "5173:5173"
        depends_on:
            - backend
